###
POST http://localhost:3002/notService/addNotebook
Content-Type: application/json

{
   "title": "Notebook 1",
   "content": "This is a notebook"
}

###
GET http://localhost:3002/notService/getNotebooks
Content-Type: application/json

###

GET http://localhost:3002/notService/getNotebook/D9A3AB1F-F8AC-4498-88E5-FEB313F2C06E
Content-Type: application/json